name: Create Environment

description: Create Azure ML environment if one does not exist.

inputs:
  environment_file:
    description: Local path to the YAML file containing the Azure ML environment specification
    required: true
  azure_credentials:
    description: JSON object for the service principal used to authenticate with Azure
    required: true

runs:
  using: "composite"

  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - uses: frenck/action-setup-yq@latest

    - name: Create environment
      shell: bash
      run: |
        ENVIRONMENT_NAME=$(yq '.name' < ${{ inputs.environment_file }})
        ENVIRONMENT_VERSION=$(yq '.version' < ${{ inputs.environment_file }})
        ENVIRONMENT_EXISTS=$(az ml environment list --name $ENVIRONMENT_NAME --query "[?version=='$ENVIRONMENT_VERSION']" | wc -l)

        if [[ $ENVIRONMENT_EXISTS -ne 1 ]]; then
            az ml environment create --file ${{ inputs.environment_file }}
        else
            echo "Environment exists"
        fi
