$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: main
code_configuration:
  code: ../../src
  scoring_script: online_score.py
endpoint_name: employee-attrition-oe
environment: azureml:employee-attrition-score@latest
model: azureml:employee-attrition@latest
instance_type: Standard_F2s_v2
instance_count: 1
app_insights_enabled: true
