$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: employee-attrition-train
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: conda/train.yml
description: Training environment for the employee attrition model.
