$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: employee-attrition-drift-pipeline
experiment_name: employee-attrition-drift-pipeline
description: Pipeline to measure data drift between a reference dataset and target dataset.

inputs:
  reference_data:
    type: mltable
    path: azureml:employee-attrition-curated@latest
  target_data:
    type: mltable
    path: azureml:employee-attrition-inference-batch@latest

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  data_drift_step:
    type: command
    environment_variables:
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=${INSTRUMENTATION_KEY} # example: "InstrumentationKey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    inputs:
      reference_data: ${{parent.inputs.reference_data}}
      target_data: ${{parent.inputs.target_data}}
      model_name: employee-attrition
    code: ..
    environment: azureml:employee-attrition-drift@latest
    command: >-
      python src/drift.py 
      --model_name ${{inputs.model_name}} 
      --reference_data ${{inputs.reference_data}}
      --target_data ${{inputs.target_data}}
