$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: employee-attrition-drift-pipeline
experiment_name: employee-attrition-drift-pipeline
description: Pipeline to measure data drift between a reference dataset and target dataset.

inputs:
  reference_data:
    type: mltable
    path: azureml:employee-attrition-curated-mltable@latest
  target_data:
    type: mltable
    path: azureml:employee-attrition-inference-mltable@latest

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  data_drift_step:
    type: command
    component: file:../components/drift.yml
    environment_variables:
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=4a49e5d4-47bf-4d27-b1f6-7b08cae81fcf # example: "InstrumentationKey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    inputs:
      reference_data: ${{parent.inputs.reference_data}}
      target_data: ${{parent.inputs.target_data}}
