$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: employee-attrition-pipeline
experiment_name: employee-attrition-pipeline
description: Pipeline to build an MLFlow model to determine the likelihood of employee attrition.

inputs:
  curated_dataset:
    type: uri_folder
    path: azureml:employee-attrition-curated@latest

outputs:
  prepared_data_dir:
    mode: rw_mount

  model_artifact_dir:
    mode: rw_mount

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prepare_step:
    type: command
    component: ../components/prepare.yml
    inputs:
      curated_dataset: ${{parent.inputs.curated_dataset}}
    outputs:
      prepared_data_dir: ${{parent.outputs.prepared_data_dir}}

  data_quality_step:
    type: command
    component: ../components/data_quality.yml
    inputs:
      prepared_data_dir: ${{parent.jobs.prepare_step.outputs.prepared_data_dir}}

  sweep_step:
    type: sweep
    trial: ../components/train.yml
    inputs:
      prepared_data_dir: ${{parent.jobs.prepare_step.outputs.prepared_data_dir}}
      random_state: 42
    outputs:
      model_output: ${{parent.outputs.model_artifact_dir}}
    sampling_algorithm: random
    search_space:
      n_estimators:
        type: uniform
        min_value: 100
        max_value: 1000
      max_depth:
        type: uniform
        min_value: 1
        max_value: 25
      criterion:
        type: choice
        values: ["gini", "entropy"]
    objective:
      primary_metric: validation_f1_score
      goal: maximize
    limits:
      max_total_trials: 2
      max_concurrent_trials: 2
      timeout: 720

  register_step:
    type: command
    component: ../components/register.yml
    inputs:
      model_name: employee-attrition
      model_output: ${{parent.jobs.sweep_step.outputs.model_output}}
      prepared_data_dir: ${{parent.jobs.prepare_step.outputs.prepared_data_dir}}
      conda_env: environments/conda/score.yml
