name: employee-attrition-train

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.5
  - pip=20.1.1
  - pip:
      - azureml-defaults~=1.42.0
      - azure-ai-ml
      - azureml-core~=1.42.0
      - azureml-mlflow~=1.42.0
      - deepchecks~=0.8.2
      - ipykernel~=6.0
      - matplotlib~=3.5.0
      - numpy~=1.19.5
      - pandas~=1.1.5
      - psutil~=5.8.0
      - scikit-learn~=1.0.2
      - scipy~=1.7.0
      - tqdm~=4.62.0
