name: employee-attrition-train

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8.5
  - pip=20.1.1
  - pip:
      - azureml-defaults~=1.47.0
      - azure-ai-ml~=1.1.2
      - azureml-core~=1.47.0
      - azureml-mlflow~=1.47.0
      - deepchecks~=0.8.2
      - ipykernel~=6.0
      - matplotlib~=3.5.0
      - mltable~=0.1.0b4
      - numpy~=1.23.0
      - pandas~=1.5.0
      - psutil~=5.8.0
      - scikit-learn~=1.1.0
      - scipy~=1.7.0
      - tqdm~=4.62.0
