$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: employee-attrition-drift-pipeline-schedule
display_name: employee-attrition-drift-pipeline-schedule
description: Recurring job scheduled to measure data drift between a reference dataset and target dataset.

trigger:
  type: cron
  expression: "0 0 * * 0"

create_job: core/pipelines/train_model.yml
