$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: employee-attrition-export-pipeline-schedule
display_name: employee-attrition-export-pipeline-schedule
description: Recurring job scheduled to export inference data from log analytics workspace and write to storage.

trigger:
  type: cron
  expression: "0 0 * * 0"

create_job: ../pipelines/data_export.yml
