$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: credit-card-default-drift-schedule
display_name: credit-card-default-drift-schedule
description: Recurring job scheduled to measure data drift between a reference dataset and target dataset.

trigger:
  type: cron
  expression: "0 0 * * 0"

create_job: ../pipelines/data_drift.yml
