name: Create deployment

description: Create Azure ML deployment if one does not exist.

inputs:
  deployment_type:
    description: Type of the deployment
    required: true
  deployment_file:
    description: Local path to the YAML file containing the Azure ML deployment specification
    required: true
  endpoint_file:
    description: Local path to the YAML file containing the Azure ML endpoint specification
    required: true
  endpoint_suffix:
    description: Unique identifier to append to endpoint name
    required: true

runs:
  using: "composite"

  steps:
    - name: Create deployment
      shell: bash
      run: |
        ENDPOINT_NAME=$(yq '.name' < ${{ inputs.endpoint_file }})-${{ inputs.endpoint_suffix }}
        DEPLOYMENT_NAME=$(yq '.name' < ${{ inputs.deployment_file }})
        DEPLOYMENT_EXISTS=$(az ml ${{ inputs.deployment_type }}-deployment list --endpoint-name $ENDPOINT_NAME -o tsv --query "[?name=='$DEPLOYMENT_NAME'][name]" | wc -l)
        echo $ENDPOINT_NAME $DEPLOYMENT_NAME $DEPLOYMENT_EXISTS

        if [[ $DEPLOYMENT_EXISTS -ne 1 ]]; then
            echo "Creating deployment"
            az ml ${{ inputs.deployment_type }}-deployment create --name $DEPLOYMENT_NAME --endpoint $ENDPOINT_NAME --file ${{ inputs.deployment_file }} \
              --set tags.github_run_id=${{ github.run_id }} tags.github_workflow_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        else
            echo "Updating deployment"

            if [[ "${{ inputs.deployment_type }}" == "online" ]]; then    
                echo "Updating traffic for online endpoint deployment"
                az ml ${{ inputs.deployment_type }}-endpoint update --name $ENDPOINT_NAME --traffic "${DEPLOYMENT_NAME}=0"
            fi

            az ml ${{ inputs.deployment_type }}-deployment delete --name $DEPLOYMENT_NAME --endpoint $ENDPOINT_NAME --yes
            az ml ${{ inputs.deployment_type }}-deployment create --name $DEPLOYMENT_NAME --endpoint $ENDPOINT_NAME --file ${{ inputs.deployment_file }} \
              --set tags.github_run_id=${{ github.run_id }} tags.github_workflow_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        fi
