name: Build Workflow

on:
  push:
    branches:
      - workflow
  workflow_dispatch:

jobs:
  code-quality:
    name: Code scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  train-model:
    name: Train model
    runs-on: ubuntu-latest

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI v2
        run: |
          set -e # fail on error
          az version
          az extension add -n ml -y
          az extension update -n ml

      - name: Install yq
        run: sudo snap install yq

      - name: Set default azureml resource group and workspace
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az configure --defaults group=${{ secrets.WORKSPACE_RESOURCE_GROUP }} workspace=${{ secrets.WORKSPACE_NAME }}

      - name: Create training environment
        uses: "./.github/template/create-environment"
        with:
          environment_file: ./core/environments/train.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create scoring environment
        uses: "./.github/template/create-environment"
        with:
          environment_file: ./core/environments/score.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create drift environment
        uses: "./.github/template/create-environment"
        with:
          environment_file: ./core/environments/drift.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run pipeline job to train model
        uses: "./.github/template/run-job"
        with:
          job_file: ./core/pipelines/train_model.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
