name: Code Quality

on:
  push: # Runs workflow when you push a commit or tag
    branches:
      - main
      - development

  schedule: # Runs workflow at a scheduled time.
    - cron: "0 0 * * 0"

jobs:
  code-quality:
    name: Code Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2
