name: Create Data Assets

on:
  push:
    branches:
      - workflow
  workflow_dispatch:

jobs:
  create-data-assets-staging:
    name: Create Data Assets in Staging
    runs-on: ubuntu-latest

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/template/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.WORKSPACE_RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create curated data asset
        uses: "./.github/template/create-data-asset"
        with:
          environment_file: ./core/data/curated.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create inference data asset
        uses: "./.github/template/create-data-asset"
        with:
          environment_file: ./core/data/inference.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  create-data-assets-production:
    name: Create Data Assets in Production
    runs-on: ubuntu-latest
    needs: create-data-assets-staging

    environment:
      name: Production

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/template/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.WORKSPACE_RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create curated data asset
        uses: "./.github/template/create-data-asset"
        with:
          environment_file: ./core/data/curated.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create inference data asset
        uses: "./.github/template/create-data-asset"
        with:
          environment_file: ./core/data/inference.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
