name: Deploy to Azure Data Factory

on:
  workflow_run:
    workflows:
      - Build Azure Data Factory
    types:
      - completed

jobs:
  deploy-staging:
    name: Deploy Templates to Staging
    runs-on: ubuntu-latest

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: "./.github/templates/download-workflow-artifact"
        with:
          artifact_name: artifacts

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Deploy template
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: adf${{ secrets.WORKLOAD_IDENTIFIER }}${{ secrets.RESOURCE_INSTANCE }}
          armTemplateFile: ARMTemplateForFactory${{ secrets.RESOURCE_INSTANCE }}.json
          armTemplateParametersFile: ARMTemplateParametersForFactory${{ secrets.RESOURCE_INSTANCE }}.json

  deploy-production:
    name: Deploy Templates to Production
    runs-on: ubuntu-latest
    needs: deploy-staging

    environment:
      name: Production

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: "./.github/templates/download-workflow-artifact"
        with:
          artifact_name: artifacts

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Deploy template
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          dataFactoryName: adf${{ secrets.WORKLOAD_IDENTIFIER }}${{ secrets.RESOURCE_INSTANCE }}
          armTemplateFile: ARMTemplateForFactory${{ secrets.RESOURCE_INSTANCE }}.json
          armTemplateParametersFile: ARMTemplateParametersForFactory${{ secrets.RESOURCE_INSTANCE }}.json
