name: Build Data Assets

on:
  workflow_dispatch: # For demonstration purposes

  # push: # Runs workflow when you push a commit or tag
  #   branches:
  #     - main

  # schedule: # Runs workflow at a scheduled time.
  #   - cron: "0 0 * * 0"

jobs:
  register-data-assets-staging:
    name: Register Data Assets in Staging
    runs-on: ubuntu-latest

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: "./.github/templates/install-dependencies"
        with:
          workspace_resource_group: ${{ vars.RESOURCE_GROUP }}
          workspace_name: mlw${{ vars.WORKLOAD_IDENTIFIER }}${{ vars.RESOURCE_INSTANCE }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register curated data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/curated.yml

      - name: Create batch inference data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/inference-batch.yml

      - name: Create online inference data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/inference-online.yml

  register-data-assets-production:
    name: Register Data Assets in Production
    runs-on: ubuntu-latest
    needs: register-data-assets-staging

    environment:
      name: Production

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: "./.github/templates/install-dependencies"
        with:
          workspace_resource_group: ${{ vars.RESOURCE_GROUP }}
          workspace_name: mlw${{ vars.WORKLOAD_IDENTIFIER }}${{ vars.RESOURCE_INSTANCE }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register curated data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/curated.yml

      - name: Create batch inference data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/inference-batch.yml

      - name: Create online inference data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/inference-online.yml
