name: Deploy Data Assets

on:
  workflow_dispatch: # For demonstration purposes

  # push: # Runs workflow when you push a commit or tag
  #   branches:
  #     - main

  # schedule: # Runs workflow at a scheduled time.
  #   - cron: "0 0 * * 0"

jobs:
  deploy-data-assets-staging:
    name: Deploy Data Assets in Staging
    runs-on: ubuntu-latest

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/templates/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy curated data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/curated.yml

      - name: Create inference data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/inference.yml

  deploy-data-assets-production:
    name: Deploy Data Assets in Production
    runs-on: ubuntu-latest
    needs: deploy-data-assets-staging

    environment:
      name: Production

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/templates/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy curated data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/curated.yml

      - name: Deploy inference data asset
        uses: "./.github/templates/create-data-asset"
        with:
          data_file: ./core/data/inference.yml
