name: Build and Deploy Workflow

on:
  push:
    branches:
      - workflow
  workflow_dispatch:

jobs:
  code-quality:
    name: Code scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v2

  create-model-staging:
    name: Create model in staging environment
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/template/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.WORKSPACE_RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create training environment
        uses: "./.github/template/create-environment"
        with:
          environment_file: ./core/environments/train.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create scoring environment
        uses: "./.github/template/create-environment"
        with:
          environment_file: ./core/environments/score.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create drift environment
        uses: "./.github/template/create-environment"
        with:
          environment_file: ./core/environments/drift.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run pipeline job to train model
        uses: "./.github/template/run-job"
        with:
          job_file: ./core/pipelines/train_model.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Tag model
        run: |
          echo "MODEL_NAME=$(yq '.jobs.register_step.inputs.model_name' < core/pipelines/train_model.yml)" >> $GITHUB_ENV
          echo "MODEL_VERSION=$(az ml model list --name $MODEL_NAME --query "[0].version")" >> $GITHUB_ENV

          az ml model update --name ${{ env.MODEL_NAME }} --version ${{ env.MODEL_VERSION }} \
            --set tags.github_workflow=${{ github.workflow }} tags.github_run_id=${{ github.run_id }} tags.github_run_number=${{ github.run_number }} tags.github_repository_url="https://github.com/${{ github.repository }}"

      - name: Download model
        run: |
          az ml model download --name ${{ env.MODEL_NAME }} --version ${{ env.MODEL_VERSION }}

  deploy-staging:
    name: Deploy model in staging environment
    runs-on: ubuntu-latest
    needs: create-model-staging

    environment:
      name: Staging

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: "./.github/template/install-dependencies"
        with:
          workspace_resource_group: ${{ secrets.WORKSPACE_RESOURCE_GROUP }}
          workspace_name: ${{ secrets.WORKSPACE_NAME }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create online endpoint
        uses: "./.github/template/create-endpoint"
        with:
          endpoint_type: online
          endpoint_file: ./core/deploy/online/endpoint.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create batch endpoint
        uses: "./.github/template/create-deployment"
        with:
          endpoint_type: batch
          endpoint_file: ./core/deploy/batch/endpoint.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create online deployment
        uses: "./.github/template/create-endpoint"
        with:
          deployment_type: online
          deployment_file: ./core/deploy/online/deployment.yml
          endpoint_file: ./core/deploy/online/endpoint.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create batch deployment
        uses: "./.github/template/create-deployment"
        with:
          deployment_type: batch
          deployment_file: ./core/deploy/batch/deployment.yml
          endpoint_file: ./core/deploy/batch/endpoint.yml
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
