name: Release Workflow

on:
  repository_dispatch:
    types:
      - release-workflow

jobs:
  staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Event Details
        run: |
          echo "Event triggered by $GITHUB_EVENT_NAME"
          echo "Dispatch type ${{ github.event.action }}"
          echo "Client payload ${{ github.event.client_payload.unit }}"
