name: Create deployment

description: Create Azure ML deployment if one does not exist.

inputs:
  deployment_type:
    description: Type of the deployment
    required: true
  deployment_file:
    description: Local path to the YAML file containing the Azure ML deployment specification
    required: true
  endpoint_file:
    description: Local path to the YAML file containing the Azure ML endpoint specification
    required: true
  azure_credentials:
    description: JSON object for the service principal used to authenticate with Azure
    required: true
  unique_id:
    description: Unique identifier to append to endpoint name
    required: true

runs:
  using: "composite"

  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Create deployment
      shell: bash
      run: |
        ENDPOINT_NAME=$(yq '.name' < ${{ inputs.endpoint_file }})-${{ inputs.unique_id }}
        DEPLOYMENT_NAME=$(yq '.name' < ${{ inputs.deployment_file }})
        echo $ENDPOINT_NAME $DEPLOYMENT_NAME

        az ml ${{ inputs.deployment_type }}-deployment create --name $DEPLOYMENT_NAME --endpoint $ENDPOINT_NAME --file ${{ inputs.deployment_file }}
